# Generated by Django 3.1 on 2020-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('payment', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('message', models.CharField(default='', max_length=200)),
                ('order', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
